package metadata.parser;

public enum TokenType {
  IDENTIFIER, STRING, EOF, IGNORE, EQUAL
/*  ERROR, STAR, DIV, PLUS, MINUS, NEQ, LOWER, GEQ, LEQ, GREATER, PERIOD, RANGE, COMMA, OPEN_ARRAY, CLOSE_ARRAY, CLOSEPAREN, BECOMES, THEN, DO, OF, OPENPAREN, NUMBER,
  ,
  SEMI, ELSE, IF, EF, WHILE, CASE, FOR, RETURN, COLON, OR, VAR, CONST, FUNCTION, END, NOT, MOD, AND, IMPLEMENTATION, ELEMENTARY, COMPOSITION, HFSM,
  RECORD, UNION, ENUM, IMPORT, INTERFACE, INPUT, OUTPUT,
  SYNC_MSG, ASYNC_MSG,
  OPENCURLY, CLOSECURLY, SHR, SHL, CONNECTION, TYPE_SEC, FALSE, TRUE,
  TRANSITION, STATE, TO, BY, ENTRY, EXIT, COMPONENT*/

}
