package parser;

//TODO cleanup, remove unused tokens
public enum TokenType {
  ERROR, STAR, DIV, PLUS, MINUS, EQUAL, NEQ, LOWER, GEQ, LEQ, GREATER, PERIOD, RANGE, COMMA, OPEN_ARRAY, CLOSE_ARRAY, CLOSEPAREN, BECOMES, THEN, DO, OF, OPENPAREN, NUMBER, IDENTIFIER, SEMI, ELSE, IF, EF, WHILE, CASE, FOR, RETURN, EOF, IGNORE, COLON, OR, CONST, FUNCTION, PROCEDURE, END, NOT, MOD, AND, ELEMENTARY, COMPOSITION, HFSM, RECORD, UNION, ENUM, IMPORT, QUERY, RESPONSE, SIGNAL, SLOT, INTERRUPT, SYNC_MSG, ASYNC_MSG, OPENCURLY, CLOSECURLY, SHR, SHL, FALSE, TRUE, STRING, STATE, TO, BY, ENTRY, EXIT, IS, AS, IN, REGISTER

}
