package parser;

public enum TokenType {
  ERROR, STAR, DIV, PLUS, MINUS, EQUAL, NEQ, LOWER, GEQ, LEQ, GREATER, PERIOD, RANGE, COMMA, OPEN_ARRAY, CLOSE_ARRAY, CLOSEPAREN, BECOMES, THEN, DO, OF, OPENPAREN, NUMBER, IDENTIFIER, SEMI, ELSE, IF, EF, WHILE, CASE, FOR, RETURN, EOF, IGNORE, COLON, OR, VAR, CONST, FUNCTION, END, NOT, MOD, AND, IMPLEMENTATION, ELEMENTARY, COMPOSITION, HFSM, RECORD, UNION, ENUM, IMPORT, QUERY, RESPONSE, SIGNAL, SLOT, INTERRUPT, SYNC_MSG, ASYNC_MSG, OPENCURLY, CLOSECURLY, SHR, SHL, CONNECTION, TYPE_SEC, FALSE, TRUE, STRING, TRANSITION, STATE, TO, BY, ENTRY, EXIT, COMPONENT, IS, AS, IN

}
